name: Compilar Framerate Vigilante

on:
  workflow_dispatch: # Permite rodar o script manualmente clicando em um botão

jobs:
  build:
    name: Build ASI
    runs-on: windows-2022

    steps:
      - name: Baixar o código do Framerate Vigilante
        uses: actions/checkout@v4

      - name: Baixar o plugin-sdk (Requisito)
        uses: actions/checkout@v4
        with:
          repository: DK22Pac/plugin-sdk
          path: plugin-sdk
          submodules: true

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Compilar o Mod
        shell: cmd
        run: |
          echo "Compilando o projeto..."
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\plugin-sdk
          msbuild FramerateVigilante.sln /p:Configuration=Release /p:Platform=x86 /m

      - name: Disponibilizar o arquivo .ASI para download
        uses: actions/upload-artifact@v4
        with:
          name: FramerateVigilante-Modificado
          path: '**/*.asi'
          if-no-files-found: error
